# 键值

KEYCODE_MENU = 82
KEYCODE_BACK = 4
KEYCODE_HOME = 3
KEYCODE_VOLUME_UP = 24
KEYCODE_VOLUME_DOWN = 25

KEYCODE_DPAD_CENTER = 23
KEYCODE_DPAD_UP = 19
KEYCODE_DPAD_DOWN = 20
KEYCODE_DPAD_LEFT = 21
KEYCODE_DPAD_RIGHT = 22
